### ISSUE TITLE
Validations into haml

### ISSUE THREAD

**Issue by mboneil10** [umts/st-pax#11]
I notice that validations are only present in the models. I think that it would be great to add another layer of protection by validating the same things in the haml.

**Comment by dfaulken** [comment]
I don't think it's necessary - Rails handles this. Also, you only have to define your validations in one place this way, rather than needing to change a model file and then also a bunch of HAML if you decide something needs to be / doesn't need to be present or whatever.

Worth noting that Rails scaffolding, which the project devs were advised to follow, doesn't include HTML `required` tags.

**Comment by mboneil10** [comment]
Okay! I agree.
