### ISSUE TITLE
Add edit button to dispatch log

### ISSUE THREAD

**Issue by Anbranin** [umts/st-pax#155]
I don't know why you can't edit your old comments, but it'd be nice.

**Comment by werebus** [comment]
Two thoughts:

1. Some people have philosophical opinions about the permanence of "logs". Most folks would agree with allowing fixing typos, but some people might object to folks changing the substance of an entry from two weeks ago.
2. Not having editing means you don't have to implement access control on who can edit whose logs.

**Comment by Anbranin** [comment]
That makes sense! Well, people can already delete their own logs; so the access-control is already in place. It was suggested in the meeting that one should be able to edit as well, and there was agreement amongst the supervisors that they would like that.

**Comment by werebus** [comment]
Yes, if users can delete entries then they may as well be able to modify them (since you can simulate modification by deleting and re-creating).

And indeed access control is all set:

https://github.com/umts/st-pax/blob/34883cd0d51a17366e320a0ed255dd6bccf7c13f/app/models/user.rb#L16-L18

Although perhaps the method name should be changed.
