### ISSUE TITLE
Email already in use issue

### ISSUE THREAD

**Issue by umasstransit** [umts/st-pax#206]
I attempted to re-register a Permanent passenger but couldnt seem to do so as it kept saying the spire ID or email was already in use. 

[90](https://st-pax.admin.umass.edu/users/90)

**Comment by werebus** [comment]
@Anbranin, If I recall correctly, we couldn't reproduce this, right?

**Comment by Anbranin** [comment]
Correct. We could not reproduce it without doing something incorrect on the part of the user--that is, pressing enter to submit the form.
It should no longer be a problem due to dispatchers being able to see the archived passengers and indeed I have heard nothing. Closing this issue until we hear something else, which will probably be in the form of a new issue.
