### ISSUE TITLE
Archive Passenger Error

### ISSUE THREAD

**Issue by umasstransit** [umts/st-pax#236]
I am trying to archive a permanent passenger and I am getting an error message. It says:
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

[71](https://st-pax.admin.umass.edu/users/71)

**Comment by BenMelz** [comment]
`550 5.1.1 <msenfuma@umass.edu>: Recipient address rejected: User unknown in relay recipient table`

> 550 5.1.1 means that the recipient email server considers that the email address doesn't exist at the destination domain, and therefore has no way to deliver it. Unless you made an error typing out in the email address, this is not something for you to correct and needs to be corrected on the receiving end.

It seems sending a notification email to `msenfuma@umass.edu` is returning an error that that particular email does not exist. If the email does actually exist it seems this isn't a problem with the app itself. 

If the email actually doesn't exist I'm not sure how error handling should be processed. Still block the archival and flash an error? Or archive and flash a warning that no email was delivered?

**Comment by werebus** [comment]
> archive and flash a warning that no email was delivered?

This one. There's not much the staff can do if the email is incorrect (or deactivated) and the passenger has left the University. They want to deactivate the employee, we should let them

Interestingly, we only get this _immediate_ 550 error because we're emailing an `@umass.edu` address by directly authenticating with a UMass email server. Otherwise this would bounce _eventually_ but not be an error.

In round three, we `rescue Net::SMTPFatalError` a few places. That's what we should do here and warn the person attempting the action.
