### ISSUE TITLE
Color inactive passengers grey

### ISSUE THREAD

**Issue by AkivaGreen** [umts/st-pax#40]
If you check the show inactive box it doesn't get the inactive passengers.

**Comment by dfaulken** [comment]
Can you substiantiate this in any way? Because I see this:

Unchecked:
<img width="842" alt="screen shot 2017-08-25 at 1 56 13 pm" src="https://user-images.githubusercontent.com/3988134/29726329-4531e48a-899d-11e7-8d58-cb56ed8318dc.png">


Checked:
<img width="817" alt="screen shot 2017-08-25 at 1 55 49 pm" src="https://user-images.githubusercontent.com/3988134/29726293-252e94b2-899d-11e7-9a79-a88945ee8b36.png">

Note the addition of "Allena Donnelly".

**Comment by Chauce** [comment]
It was working before we moved Doctors Note to its own table; I'm guessing it's just something we forgot to integrate? "Show Inactive" should be the PAX who are colored grey (3 days past expiration they go inactive, because Andrew wanted them to have a bit of a grace period).

**Comment by dfaulken** [comment]
But am I not seeing an inactive passenger in my screenshot above?

Or are you saying that the actual issue here is that the coloring is wrong? And the checkbox is fine?

**Comment by Chauce** [comment]
Oops, I missed that it was All + Inactive and not just Inactive. However, the coloring is actually wrong. Inactive passengers should should show up with a grey background.
